# Generated by Django 5.0.2 on 2024-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
