# Generated by Django 5.0.2 on 2024-02-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_alter_like_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='like',
            name='counts',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tube.tag'),
        ),
    ]
