# Generated by Django 5.0.2 on 2024-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.CharField(default='img/product/product_1.png', max_length=200),
        ),
    ]
